=== aerande/SOA/SOA_Project/bin/DTD/Employees.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT Employees (Employee)+>
<!ATTLIST Employees
  xmlns CDATA #FIXED ''>

<!ELEMENT Employee (EmployeeID,FirstName,LastName,Email,Extension,
                    HomePhone,CellPhone,JobTitle,SocialSecurityNumber,
                    DriverLicenseNumber,Address,City,State,PostalCode,
                    Birthdate,DateHired,Salary,Notes)>
<!ATTLIST Employee
  xmlns CDATA #FIXED ''>

<!ELEMENT EmployeeID (#PCDATA)>
<!ATTLIST EmployeeID
  xmlns CDATA #FIXED ''>

<!ELEMENT FirstName (#PCDATA)>
<!ATTLIST FirstName
  xmlns CDATA #FIXED ''>

<!ELEMENT LastName (#PCDATA)>
<!ATTLIST LastName
  xmlns CDATA #FIXED ''>

<!ELEMENT Email (#PCDATA)>
<!ATTLIST Email
  xmlns CDATA #FIXED ''>

<!ELEMENT Extension (#PCDATA)>
<!ATTLIST Extension
  xmlns CDATA #FIXED ''>

<!ELEMENT HomePhone (#PCDATA)>
<!ATTLIST HomePhone
  xmlns CDATA #FIXED ''>

<!ELEMENT CellPhone (#PCDATA)>
<!ATTLIST CellPhone
  xmlns CDATA #FIXED ''>

<!ELEMENT JobTitle (#PCDATA)>
<!ATTLIST JobTitle
  xmlns CDATA #FIXED ''>

<!ELEMENT SocialSecurityNumber (#PCDATA)>
<!ATTLIST SocialSecurityNumber
  xmlns CDATA #FIXED ''>

<!ELEMENT DriverLicenseNumber (#PCDATA)>
<!ATTLIST DriverLicenseNumber
  xmlns CDATA #FIXED ''>

<!ELEMENT Address (#PCDATA)>
<!ATTLIST Address
  xmlns CDATA #FIXED ''>

<!ELEMENT City (#PCDATA)>
<!ATTLIST City
  xmlns CDATA #FIXED ''>

<!ELEMENT State (#PCDATA)>
<!ATTLIST State
  xmlns CDATA #FIXED ''>

<!ELEMENT PostalCode (#PCDATA)>
<!ATTLIST PostalCode
  xmlns CDATA #FIXED ''>

<!ELEMENT Birthdate (#PCDATA)>
<!ATTLIST Birthdate
  xmlns CDATA #FIXED ''>

<!ELEMENT DateHired (#PCDATA)>
<!ATTLIST DateHired
  xmlns CDATA #FIXED ''>

<!ELEMENT Salary (#PCDATA)>
<!ATTLIST Salary
  xmlns CDATA #FIXED ''>

<!ELEMENT Notes (#PCDATA)>
<!ATTLIST Notes
  xmlns CDATA #FIXED ''>

=== aerande/SOA/SOA_Project/bin/XML/Employees.xml
<?xml version="1.0"?>
<!DOCTYPE Employees SYSTEM "C:\\Users\aniru\eclipse-workspace\SOA_Project\src\DTD\Employees.dtd">

<Employees xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="C:\\Users\aniru\eclipse-workspace\SOA_Project\src\XSD\Employees.xsd">
	<Employee>
		<EmployeeID>EID1</EmployeeID>
		<FirstName>Ned</FirstName>
		<LastName>Strak</LastName>
		<Email>nedst@gmail.com</Email>
		<Extension>291</Extension> 
		<HomePhone>1194023732</HomePhone>
		<CellPhone>1174391220</CellPhone>
		<JobTitle>Driver</JobTitle> 
		<SocialSecurityNumber>909882123</SocialSecurityNumber> 
		<DriverLicenseNumber>D12021098</DriverLicenseNumber>
		<Address>West Saint Road</Address>
		<City>winterfell</City>
		<State>Winterfell</State>
		<PostalCode>12345</PostalCode>
		<Birthdate>3-Jan-1973</Birthdate>
		<DateHired>12-May-2000</DateHired> 
		<Salary>3000</Salary>
		<Notes>Drives well</Notes>
	</Employee>
	
	<Employee>
		<EmployeeID>EID2</EmployeeID>
		<FirstName>Catlyn</FirstName>
		<LastName>Stark</LastName>
		<Email>cats@hotmail.com</Email>
		<Extension>433</Extension> 
		<HomePhone>1293210332</HomePhone>
		<CellPhone>1128940552</CellPhone>
		<JobTitle>Driver</JobTitle> 
		<SocialSecurityNumber>556234100</SocialSecurityNumber> 
		<DriverLicenseNumber>D12931098</DriverLicenseNumber>
		<Address>Pastel Pond Park</Address>
		<City>Winterfell</City>
		<State>Winterfell</State>
		<PostalCode>12345</PostalCode>
		<Birthdate>16-June-1982</Birthdate>
		<DateHired>7-Nov-2010</DateHired> 
		<Salary>2000</Salary>
		<Notes>Drives well</Notes>
	</Employee>
	
	<Employee>
		<EmployeeID>EID3</EmployeeID>
		<FirstName>Adam</FirstName>
		<LastName>Le</LastName>
		<Email>ale@hotmail.com</Email>
		<Extension>123</Extension> 
		<HomePhone>1218756093</HomePhone>
		<CellPhone>1173402385</CellPhone>
		<JobTitle>Driver</JobTitle> 
		<SocialSecurityNumber>765214092</SocialSecurityNumber> 
		<DriverLicenseNumber>G51035612</DriverLicenseNumber>
		<Address>St.Paul street</Address>
		<City>New Jersey</City>
		<State>New Jersey</State>
		<PostalCode>67309</PostalCode>
		<Birthdate>24-Feb-1988</Birthdate>
		<DateHired>3-Feb-2014 </DateHired> 
		<Salary>2500</Salary>
		<Notes>Did well</Notes>
	</Employee>
	
	<Employee>
		<EmployeeID>EID4</EmployeeID>
		<FirstName>John</FirstName>
		<LastName>May</LastName>
		<Email>jmay@yahoo.com</Email>
		<Extension>203</Extension> 
		<HomePhone>1368912526</HomePhone>
		<CellPhone>1126720413</CellPhone>
		<JobTitle>Driver</JobTitle> 
		<SocialSecurityNumber>894213562</SocialSecurityNumber> 
		<DriverLicenseNumber>O36713253</DriverLicenseNumber>
		<Address>Martin Road</Address>
		<City>Chicago</City>
		<State>Illinois</State>
		<PostalCode>60616</PostalCode>
		<Birthdate>3-May-1980 </Birthdate>
		<DateHired>20-Apr-1999</DateHired> 
		<Salary>4500</Salary>
		<Notes>Good</Notes>
	</Employee>
	
	<Employee>
		<EmployeeID>EID5</EmployeeID>
		<FirstName>Tony</FirstName>
		<LastName>Rao</LastName>
		<Email>trao@gmail.com</Email>
		<Extension>833</Extension> 
		<HomePhone>1178904576</HomePhone>
		<CellPhone>1671435091</CellPhone>
		<JobTitle>Driver</JobTitle> 
		<SocialSecurityNumber>461298652</SocialSecurityNumber> 
		<DriverLicenseNumber>Z36715612</DriverLicenseNumber>
		<Address>18th St. Lake</Address>
		<City>Chicago</City>
		<State>Illinois</State>
		<PostalCode>56476</PostalCode>
		<Birthdate>6-Dec-1985</Birthdate>
		<DateHired>23-Sep-2010</DateHired> 
		<Salary>2300</Salary>
		<Notes>Helper</Notes>
	</Employee>
	
	<Employee>
		<EmployeeID>EID6</EmployeeID>
		<FirstName>Jon</FirstName>
		<LastName>Snow</LastName>
		<Email>jsnow@gmail.com</Email>
		<Extension>211</Extension> 
		<HomePhone>1129843014</HomePhone>
		<CellPhone>1174329043</CellPhone>
		<JobTitle>Driver</JobTitle> 
		<SocialSecurityNumber>678120932</SocialSecurityNumber> 
		<DriverLicenseNumber>M12095434</DriverLicenseNumber>
		<Address>Inter State Path</Address>
		<City>Castleblack</City>
		<State>Castleblack</State>
		<PostalCode>57373</PostalCode>
		<Birthdate>23-Sep-1990 </Birthdate>
		<DateHired>1-Nov-2009</DateHired> 
		<Salary>1000</Salary>
		<Notes>Good</Notes>
	</Employee>
	
	<Employee>
		<EmployeeID>EID7</EmployeeID>
		<FirstName>Tim</FirstName>
		<LastName>Ku</LastName>
		<Email>tku@gmail.com</Email>
		<Extension>871</Extension> 
		<HomePhone>2134678231</HomePhone>
		<CellPhone>1179095436</CellPhone>
		<JobTitle>Driver</JobTitle> 
		<SocialSecurityNumber>676234891</SocialSecurityNumber> 
		<DriverLicenseNumber>N19430253</DriverLicenseNumber>
		<Address>South King Drive</Address>
		<City>Chicago</City>
		<State>Illinois</State>
		<PostalCode>31984</PostalCode>
		<Birthdate>2-May-1981</Birthdate>
		<DateHired>10-Jan-2013</DateHired> 
		<Salary>4500</Salary>
		<Notes>Drives big truck</Notes>
	</Employee>
	
	<Employee>
		<EmployeeID>EID8</EmployeeID>
		<FirstName>Jamie</FirstName>
		<LastName>Lannister</LastName>
		<Email>jlannister@hotmail.com</Email>
		<Extension>124</Extension> 
		<HomePhone>1138973421</HomePhone>
		<CellPhone>1179093227</CellPhone>
		<JobTitle>Driver</JobTitle> 
		<SocialSecurityNumber>389845234</SocialSecurityNumber> 
		<DriverLicenseNumber>KJ3230TH3</DriverLicenseNumber>
		<Address>421 St. Paul</Address>
		<City>Westros</City>
		<State>Westros</State>
		<PostalCode>42782</PostalCode>
		<Birthdate>4-July-1979</Birthdate>
		<DateHired>19-Sep-2010</DateHired> 
		<Salary>2900</Salary>
		<Notes>Amount paid</Notes>
	</Employee>
	
	<Employee>
		<EmployeeID>EID9</EmployeeID>
		<FirstName>Sam</FirstName>
		<LastName>Mark</LastName>
		<Email>smark@hotmail.com</Email>
		<Extension>221</Extension> 
		<HomePhone>1167893421</HomePhone>
		<CellPhone>1179060304</CellPhone>
		<JobTitle>Driver</JobTitle> 
		<SocialSecurityNumber>787231420</SocialSecurityNumber> 
		<DriverLicenseNumber>OH3943124</DriverLicenseNumber>
		<Address>20th Market Street</Address>
		<City>New York</City>
		<State>New York</State>
		<PostalCode>56712</PostalCode>
		<Birthdate>20-Dec-1987 </Birthdate>
		<DateHired>1-Dec-2010</DateHired> 
		<Salary>3000</Salary>
		<Notes>Amount due</Notes>
	</Employee>
	
	<Employee>
		<EmployeeID>EID10</EmployeeID>
		<FirstName>Tyrion</FirstName>
		<LastName>Lannister</LastName>
		<Email>tlannister@hotmail.com </Email>
		<Extension>435</Extension> 
		<HomePhone>1317890435</HomePhone>
		<CellPhone>1178903452</CellPhone>
		<JobTitle>Driver</JobTitle> 
		<SocialSecurityNumber>267814562</SocialSecurityNumber> 
		<DriverLicenseNumber>K12984352</DriverLicenseNumber>
		<Address>King Road</Address>
		<City>Westros</City>
		<State>Westros</State>
		<PostalCode>90124</PostalCode>
		<Birthdate>9-Dec-1978</Birthdate>
		<DateHired>10-Jan- 2011</DateHired> 
		<Salary>4300</Salary>
		<Notes>Worker</Notes>
	</Employee>

</Employees>
