=== aerande/SOA/SOA_Project/src/DTD/Locations.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT Locations (Location)+>
<!ATTLIST Locations
  xmlns CDATA #FIXED ''>

<!ELEMENT Location (LocationID,LocName,LocationCode,IsAuction,
                    CustomerID,Address_Street1,Address_street2,City,
                    State,PostalCode,Region,Location_contact_name,
                    LocPhone,LocFaxNumber,LocEmail)>
<!ATTLIST Location
  xmlns CDATA #FIXED ''>

<!ELEMENT LocationID (#PCDATA)>
<!ATTLIST LocationID
  xmlns CDATA #FIXED ''>

<!ELEMENT LocName (#PCDATA)>
<!ATTLIST LocName
  xmlns CDATA #FIXED ''>

<!ELEMENT LocationCode (#PCDATA)>
<!ATTLIST LocationCode
  xmlns CDATA #FIXED ''>

<!ELEMENT IsAuction (#PCDATA)>
<!ATTLIST IsAuction
  xmlns CDATA #FIXED ''>

<!ELEMENT CustomerID (#PCDATA)>
<!ATTLIST CustomerID
  xmlns CDATA #FIXED ''>

<!ELEMENT Address_Street1 (#PCDATA)>
<!ATTLIST Address_Street1
  xmlns CDATA #FIXED ''>

<!ELEMENT Address_street2 (#PCDATA)>
<!ATTLIST Address_street2
  xmlns CDATA #FIXED ''>

<!ELEMENT City (#PCDATA)>
<!ATTLIST City
  xmlns CDATA #FIXED ''>

<!ELEMENT State (#PCDATA)>
<!ATTLIST State
  xmlns CDATA #FIXED ''>

<!ELEMENT PostalCode (#PCDATA)>
<!ATTLIST PostalCode
  xmlns CDATA #FIXED ''>

<!ELEMENT Region (#PCDATA)>
<!ATTLIST Region
  xmlns CDATA #FIXED ''>

<!ELEMENT Location_contact_name (#PCDATA)>
<!ATTLIST Location_contact_name
  xmlns CDATA #FIXED ''>

<!ELEMENT LocPhone (#PCDATA)>
<!ATTLIST LocPhone
  xmlns CDATA #FIXED ''>

<!ELEMENT LocFaxNumber (#PCDATA)>
<!ATTLIST LocFaxNumber
  xmlns CDATA #FIXED ''>

<!ELEMENT LocEmail (#PCDATA)>
<!ATTLIST LocEmail
  xmlns CDATA #FIXED ''>

=== aerande/SOA/SOA_Project/src/XML/Locations.xml
<?xml version="1.0"?>
<!DOCTYPE Locations SYSTEM "C:\\Users\aniru\eclipse-workspace\SOA_Project\src\DTD\Locations.dtd">

<Locations xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="C:\\Users\aniru\eclipse-workspace\SOA_Project\src\XSD\Locations.xsd">
	<Location>
		<LocationID>LOC1</LocationID> 
        	<LocName>Chicago</LocName> 
	        <LocationCode>CH111</LocationCode> 
        	<IsAuction>yes</IsAuction> 
		<CustomerID>CID1</CustomerID> 
        	<Address_Street1>870 Oak Valley Street</Address_Street1>
        	<Address_street2>Chicago</Address_street2> 
		<City>Chicago</City> 
		<State>ILLINOIS</State> 
		<PostalCode>60616</PostalCode>  
		<Region>CETNTRAL</Region> 
		<Location_contact_name>Ronald</Location_contact_name> 
		<LocPhone>1415598280</LocPhone> 
		<LocFaxNumber>1402658000</LocFaxNumber>
		<LocEmail>chillinois@gmail.com</LocEmail>
	</Location>	
	
	<Location>
		<LocationID>LOC2</LocationID> 
        	<LocName>Columbus</LocName> 
        	<LocationCode></LocationCode> 
        	<IsAuction>yes</IsAuction> 
		<CustomerID>CID2</CustomerID> 
	        <Address_Street1>594 Erie Point</Address_Street1>
       		<Address_street2>Columbus</Address_street2> 
		<City>Columbus</City> 
		<State>OHIO</State> 
		<PostalCode>43026</PostalCode>  
		<Region>CENTRAL</Region> 
		<Location_contact_name>Antonio</Location_contact_name> 
		<LocPhone>1731431070</LocPhone> 
		<LocFaxNumber>1504448848</LocFaxNumber>
		<LocEmail>coluhio@gmail.com</LocEmail>
	</Location>		
	
	<Location>
		<LocationID>LOC3</LocationID> 
		<LocName>New York</LocName> 
		<LocationCode>NY111</LocationCode> 
		<IsAuction>no</IsAuction> 
		<CustomerID>CID3</CustomerID> 
		<Address_Street1>18320 Shoshone Pass</Address_Street1>
		<Address_street2>newyork</Address_street2> 
		<City>New York</City> 
		<State>New York</State> 
		<PostalCode>45656</PostalCode>  
		<Region>CENTRAL</Region> 
		<Location_contact_name>Mary</Location_contact_name> 
		<LocPhone>1816961273</LocPhone> 
		<LocFaxNumber>1202385413</LocFaxNumber>
		<LocEmail>newyny@gmail.com</LocEmail>
	</Location>	
	
	<Location>
		<LocationID>LOC4</LocationID> 
		<LocName>Maryland</LocName> 
		<LocationCode>MD112</LocationCode> 
		<IsAuction>no</IsAuction> 
		<CustomerID>CID4</CustomerID> 
		<Address_Street1>2314 The Alaire</Address_Street1>
		<Address_street2>Kings Dr</Address_street2> 
		<City>Maryland</City> 
		<State>Maryland</State> 
		<PostalCode>40953</PostalCode>  
		<Region>WEST</Region> 
		<Location_contact_name>Arya</Location_contact_name> 
		<LocPhone>1202385413</LocPhone> 
		<LocFaxNumber>1202385413</LocFaxNumber>
		<LocEmail>md@gmail.com</LocEmail>
	</Location>	
	
	<Location>
		<LocationID>LOC5</LocationID> 
		<LocName>Charlotte</LocName> 
		<LocationCode>CH111</LocationCode> 
		<IsAuction>yes</IsAuction> 
		<CustomerID>CID5</CustomerID> 
		<Address_Street1>18 Legacy Pass</Address_Street1>
		<Address_street2>Cubs Dr</Address_street2> 
		<City>Charlotte</City> 
		<State>Noth Carolina</State> 
		<PostalCode>89076</PostalCode>  
		<Region>North</Region> 
		<Location_contact_name>Somu</Location_contact_name> 
		<LocPhone>1202385413</LocPhone> 
		<LocFaxNumber>1202223413</LocFaxNumber>
		<LocEmail>chnc09@gmail.com</LocEmail>
	</Location>	
</Locations>
