=== aerande/SOA/SOA_Project/src/XSD/Comments.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="http://www.w3schools.com"
xmlns="http://www.w3schools.com"
elementFormDefault="qualified">

  <xs:element name="Comments">
    <xs:complexType>
      <xs:sequence>
        <xs:element type="xs:string" name="CommentID"/>
        <xs:element type="xs:string" name="TimeStamp"/>
        <xs:element type="xs:string" name="CommentText"/>
        <xs:element type="xs:string" name="CommentType"/>
		<xs:element type="xs:string" name="CustomerID"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== aerande/SOA/SOA_Project/src/XML/Comments.xml
<?xml version="1.0"?>
<!DOCTYPE Comments SYSTEM "C:\\Users\aniru\eclipse-workspace\SOA_Project\src\DTD\Comments.dtd">

<Comments xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="C:\\Users\aniru\eclipse-workspace\SOA_Project\src\XSD\Comments.xsd">
	<Comment>
	<CommentID>CID1</CommentID> 
	<TimeStamp>28-Sep-2013 15:54:06</TimeStamp>
       	 <CommentText>Full amount paid</CommentText>
		 <CommentType>general</CommentType>
		 <CustomerID>CID1</CustomerID>
	</Comment>
	
	<Comment>
	<CommentID>CID2</CommentID>
	<TimeStamp>03-June-2012 09:12:30</TimeStamp>		
    	<CommentText>Product not received on time</CommentText>
      	 <CommentType>general</CommentType>
		 <CustomerID>CID2</CustomerID>
	</Comment>
	
	<Comment>
	<CommentID>CID3</CommentID>
	<TimeStamp>11-Feb-2006 11:12:10</TimeStamp>		
           <CommentText>Technical issues with product</CommentText>
           <CommentType>critical</CommentType>
		   <CustomerID>CID3</CustomerID>
	</Comment>
	
	<Comment>
	<CommentID>CID4</CommentID> 
	<TimeStamp>20-Mar-2016 20:26:56</TimeStamp>	
           <CommentText>Product malfunction</CommentText>
           <CommentType>critical</CommentType>
		   <CustomerID>CID4</CustomerID>
	</Comment>
</Comments>
